mysite2/boysdinner/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles import views

from django.contrib import admin
admin.autodiscover()
from boysdinner import views

urlpatterns = [
    #boysdinner root/index page: enter name, enter dish name
	#presumably is skipped if session still active
	#date identifies the dinner
    url(r'^(?P<first_name>\w+)/(?P<dish_name>\w+)/$', views.signin, name='signin'),
    url(r'^signin/$', views.signin, name='signin'),

	#on signin page allows user to search for their record
	#for eventual updating of name and and/or dish name
    url(r'^search/$', views.search_person, name='search_person'),

	#logs in proceeds to vote page where program checks to
	#see if someone has submitted to be voted upon and if yes
	# puts form at top or shows "error style" message and shows
	#all votes that user has made so far below
    url(r'^boysdinner/(?P<voter_id>\d+)/vote/$', views.vote, name='vote'),

    #processes updates to old votes prefixed forms
    url(r'^boysdinner/(?P<voter_id>\d+)/(?P<pre_fix>\d+)/old_votes/$', views.old_votes, name='old_votes'),

	#overall totals in a chart per person-name in descending order
	#so that 1st place comes first, etc
    url(r'^boysdinner/(?P<voter_id>\d+)/results/$', views.results, name='results'),

	##displays others' votes for me, per person including comments
    #url(r'^boysdinner/(?P<user_id>\d+)/mycritics/$', views.my_critics, name='my_critics'),
    #url(r'^boysdinner/(?P<user_id>\d+)/(\d{4}-\d{2}-\d{2})/mycritics/$', views.my_critics, name='my_critics'),
    url(r'^boysdinner/(?P<user_id>\d+)/(?P<raw_served_date>\w+)/mycritics/$', views.my_critics, name='my_critics'),

] 

urlpatterns += staticfiles_urlpatterns()

mysite2/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	# Examples:
	url(r'^$', 'mysite.views.home'),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^boysdinner/', include('boysdinner.urls', namespace="boysdinner")),
)

mysite2/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name="vote"),
)

mysite2/boysdinner/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
	#Changed Chefs and Critics into just Person table
	first_name = models.CharField(max_length=50)

	def __str__(self):
		return self.first_name

class Dish(models.Model):
	chef = models.ForeignKey(Person)
	dish_name = models.CharField(max_length=200)
	current_dish = models.BooleanField(default=False)
	served_date = models.DateField('Date Dish Served')
	#served_date = models.DateField('Date Dish Served',auto_now=True)

	def __str__(self):
		return self.chef.first_name+"'s "+self.dish_name

class DishVote(models.Model):
	dish = models.ForeignKey(Dish)
	critic = models.ForeignKey(Person, null=True)
	taste_rating = models.IntegerField(default=0)
	originality_rating = models.IntegerField(default=0)
	presentation_rating = models.IntegerField(default=0)
	comment = models.CharField(max_length=400,null=True, blank=True)

	def __str__(self):
		return self.critic.first_name+"'s voting record"

	class Meta:
		unique_together = (('critic', 'dish'),)

mysite2/boysdinner/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from django import forms
from django.forms import ModelForm
from boysdinner.models import Person, Dish, DishVote
import datetime
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelChoiceField
from django.utils.timezone import get_current_timezone


# Create your views here.

class IndexView(TemplateView):
	template_name = "boysdinner/index.html"

class PersonForm(ModelForm):
	class Meta:
		model = Person
		widgets = {
			'first_name': forms.TextInput({'placeholder': 'First name'})
		}
		fields = ['first_name']

class MyModelChoiceField(ModelChoiceField):
	def label_from_instance(self, obj):
		return "%s" % obj.first_name.title()

class SearchForm(ModelForm):
	try:
		person_dropdown = MyModelChoiceField(queryset= Person.objects.filter(
														dish__served_date=datetime.date.today()
																			), 
										empty_label="--Find yourself--", 
										widget=forms.Select(attrs={"onChange":'submit()'}))
	except:
		person_dropdown = "None"

	class Meta:
		model = Person
		fields = ['person_dropdown']

class ResultsModelChoiceField(ModelChoiceField):
	#this subclass exists only to change the way the option string is displayed
	def label_from_instance(self, obj):
		try:
			served_date = obj.served_date.strftime("%A %B %d, %Y")
		except:
			served_date=""

		return "%s" %served_date

class DatedResultsForm(ModelForm):
	#dropdown with all dates where there were votes
	dated_results_dropdown = ResultsModelChoiceField(

					#returns queryset
					queryset = Dish.objects.all().order_by('served_date').distinct(), 
					#returns dict
					#queryset = Dish.objects.all().order_by('served_date').values_list('served_date', flat=True).distinct(), 
					#queryset = Dish.objects.all().order_by('served_date').values_list('id','served_date').distinct(), 
					empty_label="--View past results--", 
					widget=forms.Select(attrs={"onChange":'submit()'}))
									
	class Meta:
		model = Dish
		fields = ['dated_results_dropdown']

class DishForm(ModelForm):
	dish_name = forms.CharField(widget=forms.Textarea(attrs={'cols': 20, 
										'rows': 3,'placeholder': 'Dish name'}))
	class Meta:
		model = Dish
		fields = ['id','dish_name','current_dish']

class DishVoteForm(ModelForm):
	comment = forms.CharField(widget=forms.Textarea(attrs={'cols': 20, 'rows': 5}))
	fake_id = forms.CharField(widget=forms.HiddenInput())
	class Meta:
		model = DishVote
		widgets = {
			'comment': forms.TextInput({'placeholder': 'Penny for your thoughts'})
		}
		fields = ['taste_rating','originality_rating',
					'presentation_rating','comment']
		labels = {
				'taste_rating': _('Taste Rating (1-10):'),
				'originality_rating': _('Originality Rating (1-5):'),
				'presentation_rating': _('Presentation Rating (1-5):'),
				}

def signin(request, first_name='', dish_name=''):
	first_name = first_name.lower()
	dish_name = dish_name.lower()
	error_message=""
	dish_name = dish_name.replace('_',' ')
	is_current=""
	persons = {}
	voter_id=''
	if request.method == "POST":
		form1 = PersonForm(request.POST)
		form2 = DishForm(request.POST)
		#check if form is valid
		if form1.is_valid() and form2.is_valid():
			person_name = form1.cleaned_data['first_name'].lower()
			dish_name = form2.cleaned_data['dish_name'].lower()
			current_dish = form2.cleaned_data['current_dish']
			found_person=""
			try:
				found_person = Person.objects.get(first_name=person_name)

			#this person is not in database create a new person
			except:
				new_person = form1.save(commit=False)
				new_person.first_name = person_name
				new_person.save()
				new_persons_dish = form2.save(commit=False)
				new_persons_dish = dish_name
				new_persons_dish.chef=new_person
				new_persons_dish.served_date=datetime.date.today()

				#If this is current dish, remove current status for all other dishes
				if current_dish:
					Dish.objects.all().update(current_dish=False)
					new_persons_dish.current_dish = current_dish

				new_persons_dish.save()
				voter_id = new_person.id

			#name does exist so update its dish if served today
			else:
				voter_id = found_person.id
				try:
					#get associated dish object
					todays_dish = Dish.objects.get(chef=found_person, served_date=datetime.date.today())
				#if dish exists but served on day other than today then create new dish for today
				except:
					#this is a new dish (dated for today) for existing person
					new_dish = form2.save(commit=False)
					#new_dish.dish_name = dish_name
					#now associate found_person with new dish
					new_dish.chef=found_person
					new_dish.served_date=datetime.date.today()
					#If this is current dish, remove current status for all other dishes
					if current_dish:
						Dish.objects.all().update(current_dish=False)
						new_dish.current_dish = current_dish
					new_dish.save()
					voter_id = found_person.id
				#if there exists a dish for this person served today then allow for update
				else:
					#update wording of today's dish name
					todays_dish.dish_name=dish_name
					#If this is current dish, remove current status for all other dishes
					if current_dish:
						Dish.objects.all().update(current_dish=False)
						todays_dish.current_dish = current_dish
					todays_dish.save()
					#if dish exists but served on day other than today then create new dish for today
						
			finally:
				return HttpResponseRedirect(reverse('boysdinner:vote',args=(voter_id,)))
		#form not valid:
		else:
			error_message = "Please fill all fields"
			search_form = SearchForm()

	#arrival NOT by post
	else:
		if first_name=="a":
			first_name=""
			dish_name=""
		pre_pop = {'first_name':first_name.title(),'dish_name':dish_name.title()}
		form1 = PersonForm(initial=pre_pop)
		form2 = DishForm(initial=pre_pop)
		search_form = SearchForm()
	try:
		persons = Person.objects.all()
	except:
		persons = {'first_name':'No one has logged in'}
	return render(request, 'boysdinner/index.html', 
					{'form1': form1, 
					'form2': form2,
					'search_form': search_form,
					'is_current': is_current,
					'error_message': error_message,
					'persons': persons
					}
				)

def search_person(request):
	#if post then search
	#if not post (or 1st time on page) then show page again
	pre_pop = {}
	found_person=''
	search_error=''
	if request.method == "POST":
		form = SearchForm(request.POST)
		if form.is_valid():
			try:
				#Find record (from dropdown) in database if it exists
				first_name = form.cleaned_data['person_dropdown'].first_name.lower()
				found_person = Person.objects.get(first_name=first_name)
				pre_pop['name']=found_person.first_name
				found_dish = Dish.objects.get(chef_id=found_person, served_date=datetime.date.today)
				pre_pop['dish'] = found_dish.dish_name.replace(' ','_')

				return HttpResponseRedirect(reverse('boysdinner:signin',args=(pre_pop['name'],pre_pop['dish'])))
			except:
				search_error="Misspelled name or no such user"
		else:
			search_error="Enter a name damnit!!"

	form1 = PersonForm()
	form2 = DishForm()
	search_form = SearchForm()
	is_current= False
	error_message=""

	return render(request, 'boysdinner/index.html', 
					{'form1': form1, 
					'form2': form2,
					'search_form': search_form,
					'is_current': is_current,
					'pre_pop': pre_pop,
					'search_error': search_error,
					'error_message': error_message
					}
				)

def old_votes(request, voter_id, pre_fix):
	error_message=""
	message=""
	chef_name=""
	old_votes_message=""
	is_current = False
	vote_list= []
	form0=''
	#look through database for all dishvotes with this guy's id
	#enumerate them vote1, vote2, etc. while vote is the newest one
	if request.method == "POST":
		#Process remaining forms
		votes = [DishVoteForm(request.POST, prefix=str(x)) for x in range(int(pre_fix))]
		flag="good"
		if all([vt.is_valid() for vt in votes]):
			for vt in votes:
				old_vote = vt.save(commit=False)
				if old_vote.taste_rating>10:
					flag="bad"
					error_message = "taste rating must be from 1 to 10"
				elif old_vote.originality_rating>5:
					flag="bad"
					error_message = "originality rating must be from 1 to 5"
				elif old_vote.presentation_rating>5:
					flag="bad"
					error_message = "presentation rating must be from 1 to 5"
				#everything is good go ahead and commit to database
				if flag=="good":
					#get primary key
					pk = int(vt.cleaned_data['fake_id'])
					editable_vote = DishVote.objects.get(pk=pk)
					editable_vote.taste_rating = old_vote.taste_rating
					editable_vote.originality_rating = old_vote.originality_rating
					editable_vote.presentation_rating = old_vote.presentation_rating
					editable_vote.comment = old_vote.comment
					editable_vote.save()
			return HttpResponseRedirect(reverse('boysdinner:vote', args=(voter_id,)))

				
		#submit but old votes invalid (not fully/correctly filled)
		else:
			try:
				voted_upon = Dish.objects.filter(current_dish=True)[0]
				chef_name = voted_upon.chef.first_name
			except:
				error_message = "Try again maybe from the beginning"
			error_message = "Please vote all fields"

	#arrived but not via post------------------------------
	else:
		#arriving at the page for 1st time
		#Find name of current chef being voted on and determine if current user is that person
		try:
			#[0] ensures that only the most recent record gets brought up
			chef = Dish.objects.filter(current_dish=True)[0].chef
			chef_name = chef.first_name
			if int(voter_id)==int(chef.id):
				#displayed when current voting disabled
				message = "Your head is currently on the voting bloc"
				is_current = True
		except:
			#No one has indicated that they are being voted upon
			message = "No Chef is currently on the voting bloc"

		#create newest and blank form that is to appear on top of page
		form0 = DishVoteForm(prefix=str(0))

mysite2/boysdinner/templates/boysdinner/index.html
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		{% load staticfiles %}
		<title>Boys Dinner</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
		<script src="{% static 'js/jquery.scrollgress.min.js' %}"></script>
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-layers.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-wide.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1><a href="#">Boys dinner</a></h1>
				<nav id="nav">
					<ul>
						<li><a href="{% url 'boysdinner:signin' ">Sign in</a></li>
						<li><a href="{% url 'boysdinner:results' voter_id=0 %}">Past results</a></li>
					</ul>
				</nav>
			</header>

		<!-- Main -->
			<section id="main" class="container">
				<header>
					<h2>Welcome to Boys Dinner</h2>
					<p>Conduct sign ins and updates below</p>
				</header>
				<div class="row">
					<div class="12u">
						
						<!-- Form -->
							<section class="box">
								<h3>Sign in</h3>
								{% if error_message %}<p><strong><font color="red">{{ error_message }}</font></strong></p>{% endif %}
								<form method="post" action="{% url 'boysdinner:signin' %}" method="post">
								{% csrf_token %}
								{% if not is_current %}
								{% for field in form1 %}
								<div class="row uniform half ollapse-at-2">
									<div class="6u">
										{{ field }}
									</div>
								</div>
								{% endfor %}
								{% for field in form2 %}
								<div class="row uniform half ollapse-at-2">
									<div class="6u">
										{{ field }}{{ field.label_tag }} 
									</div>
								</div>
								{% endfor %}
								{% endif %}
								<div class="row uniform half collapse-at-2">
									<div class="3u">
											<input type="submit" value="Sign in" class="fit special" />
									</div>
								</div>
								</form>
								



								<hr />
								
								<form action="{% url 'boysdinner:search_person'  %}" method="post">
								{% csrf_token %}
									<div class="row uniform half collapse-at-2">
										<div class="9u">
											{% for field in search_form %}
												{{ field }}
											{% endfor %}
										</div>
									</div>
								</form>
							</section>

					</div>
				</div>
			</section>



							
		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="http://www.facebook.com/boysdinner" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://berserk.dyndns.tv">Mayo</a></li>
				</ul>
			</footer>

	</body>
</html>

mysite2/boysdinner/templates/boysdinner/myvotes.html
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		{% load staticfiles %}
		<title>Boys Dinner</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
		<script src="{% static 'js/jquery.scrollgress.min.js' %}"></script>
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-layers.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-wide.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1><a href="{% url 'boysdinner:signin' %}">Boys Dinner</a></h1>
				<nav id="nav">
					<ul>
						<li><a href="{% url 'boysdinner:signin' %}">Change status</a></h1>
						<li>
							<a href="{% url 'boysdinner:results' voter_id %}">Results</a>
						</li>
					</ul>
				</nav>
			</header>

		<!-- Main -->
			<section id="main" class="container">
				<header>
					<h2>List of your votes</h2>
					<p>Cast your ballot {{ voter_name|title }}!</p>
				</header>
				<div class="row">
					<div class="12u">
						
						<!-- Form -->
							<section class="box">

								<section class="box">
									{% if message %}
										<h4><font color="red">{{ message }}</font></h4> 
									{% else %}
										<h3>Voting for <font color="red">{{ chef_name|title }}</font> in progress</h3> 
										{% if error_message %}
											<p><strong><font color="red">{{ error_message }} </font></strong></p>
										{% else %}
										<h3>&nbsp;</h3>
									{% endif %}
								</section>
								<form action="{% url 'boysdinner:vote' voter_id %}" method="post">
								{% csrf_token %}
								{% for field in form0 %}
									{% if field.is_hidden %}
										{{ field.field_name.as_hidden }}
									{% else %}
										{{ field.label_tag }} 
									{% endif %}
									{{ field }}
								{% endfor %}
								<div class="row uniform">
									<div class="12u">
										<input type="submit" value="Vote" class="fit" />
									</div>
								</div>
								</form>
								{% endif %}




								<div class="row">
								<div class="12u">
									<form action="{% url 'boysdinner:old_votes' voter_id pre_fix %}" method="post">
									{% csrf_token %}
									{% if old_votes_message %}
									<h5>{{ old_votes_message }}</h5>
									{% else %}
									<hr>
									<h3><center><strong>Old Votes</strong></center></h3>
									<hr>
										{% for bundle in vote_list %}
											<h3><center>{{ bundle.details.done_chef_name|title }}'s {{ bundle.details.dish_name|title }}</center></h3>
											{% for field in bundle.form %}
													{% if field.is_hidden %}
														{{ field.field_name.as_hidden }}
													{% else %}
														{{ field.label_tag }}
													{% endif %}
														{{ field }}
											{% endfor %}
											<div class="row uniform">
												<div class="12u">
													<input type="submit" value="Update" />
												</div>
											</div>
											<hr>
										{% endfor %}
									</form>
									{% endif %}
								</div>
								</div>

							</section>

					</div>
				</div>
				<div class="row">
				</div>
			</section>
			
		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="http://www.facebook.com/boysdinner" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://berserk.dyndns.tv">Mayo</a></li>
				</ul>
			</footer>

	</body>
</html>

mysite2/boysdinner/templates/boysdinner/results.html
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		{% load staticfiles %}
		<title>Boys Dinner</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
		<script src="{% static 'js/jquery.scrollgress.min.js' %}"></script>
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-layers.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-wide.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1><a href="{% url 'boysdinner:signin' %}">Boys Dinner</a></h1>
				<nav id="nav">
					<ul>
						<li><a href="{% url 'boysdinner:signin' %}">Change status</a></li>
						{% if voter_id != '0' %}
							<li>
								<a href="{% url 'boysdinner:vote' voter_id %}">Vote</a>
							</li>
						{% endif %}
					</ul>
				</nav>
			</header>

		<!-- Main -->
			<section id="main" class="container">
				<header>
					<h2>Boys Dinner Results</h2>
					<p>{{ greeting|safe }}</p>
								<center>
								<form action="{% url 'boysdinner:results'  voter_id %}" method="post">
									{% csrf_token %}
									<div class="6u">
										<select id="id_dated_results_dropdown" name="dated_results_dropdown" onChange="submit()">
										<option value="" selected="selected">--View past results--</option>
										{% for elem in old_dinners_list %}
											{% ifchanged elem.served_date %}
												<option value="{{ elem.id }}">{{ elem.served_date }}</option>
											{% endifchanged %}
										{% endfor %}
										</select>
										</div>
								</form>
								</center>
				</header>
				<div class="row">
					<div class="12u">

						<!-- Table -->
							<section class="box">
								






								<div class="table-wrapper">
									<table>
										<thead>
											<tr>
												<th><strong>Chef Name</strong></th>
												<th><strong>Total score</strong></th>
												<th><strong># of votes</strong></th>
											</tr>
										</thead>
										<tbody>
									{% for dude in totals_list %}
											<tr>
												<td>{{ dude.chef_name|title }}</td>
												<td>{{ dude.overall_score }}</td>
												{% if user_id == dude.chef_id %}
													<td><a href="{% url 'boysdinner:my_critics' user_id raw_served_date %}">{{ dude.vote_count }}</a></td>
												{% else %}
													<td>{{ dude.vote_count }}</td>
												{% endif %}
											</tr>
									{% endfor %}
										</tbody>
									</table>

								</div>
							</section>

					</div>
				</div>
			</section>
			
		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="http://facebook.com/boysdinner" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
				</ul>
			</footer>

	</body>
</html>